django_garden/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', TemplateView.as_view(template_name='pages/home.html'), name = 'home'),
    path('sensors/', include('garden.sensors.urls', namespace='sensors')),
]

django_garden/garden/sensors/urls.py
from django.urls import path
from . import views

app_name='sensors'
urlpatterns = [
    path('', views.all_sensors_view, name = 'all_sensors'),
]

django_garden/garden/sensors/models.py
from django.db import models

# Create your models here.
class Temperature(models.Model):
    """Model definition for Temperature."""

    date = models.DateTimeField(auto_now_add=True)
    temperature = models.FloatField()

    class Meta:
        verbose_name = 'Temperature'
        verbose_name_plural = 'Temperatures'

    def __str__(self):
        return str(self.date)

django_garden/garden/sensors/views.py
import serial
from django.shortcuts import render
from gpiozero import OutputDevice
from time import sleep
from .models import Temperature


def get_sensor_data():
    try:
        led = OutputDevice(17)
        led.on()
        context_dict = {}
        ser = serial.Serial('/dev/ttyUSB0')
        sleep(2)
        ser.write(b's\n')
        while True:
            if (ser.in_waiting>0):
                data = ser.readline()
                data = data.decode("ASCII")
                data = data.rstrip()
                data = data.split(',')
                print(data)
                break
    except:
        data = "Error!"
    finally:
        led.off()
        ser.close()
        return data

def all_sensors_view(request):
    context_dict = {}
    lm_temp, dh_humidity, dh_temp = get_sensor_data()
    context_dict['lm_temp'] = lm_temp
    context_dict['dh_humidity'] = dh_humidity
    context_dict['dh_temp'] = dh_temp
    return render(request, 'sensors/all_sensors.html', context_dict)

def data_view(request):
    context_dict = {}
    temperature_list = Temperature.objects.all()
    context_dict['temperature_list'] = temperature_list
    return render(request, 'sensors/data.html', context_dict)

django_garden/garden/templates/base.html
{% load staticfiles i18n %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static 'img/logo.png' %}">

    <title>Pi Garden</title>

    {% block css %}
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <!-- Bootswatch Theme -->
    <link rel="stylesheet" href="https://bootswatch.com/4/materia/bootstrap.min.css">

    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Bungee" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    {% endblock css %}

    <!-- FontAwesome 5.0.1 -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.1/js/all.js"></script>
    </head>

    <body>

    <nav class="navbar navbar-expand-md navbar-dark bg-success">
        <a class="navbar-brand" href="#">
            <img src="{% static 'img/logo.png' %}" width="30" height="30" alt="">
        </a>
        
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
            <a class="nav-link" href="{% url 'home' %}"><i class="fa fa-home"></i> Inicio<span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'sensors:all_sensors' %}"><i class="fa fa-tachometer-alt"></i> Sensores</a>
            </li>
        </ul>
        </div>
    </nav>

    <main role="main" class="container">

        {% block content %}
        {% endblock %}

    </main><!-- /.container -->

    {% block javascript %}
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
    {% endblock %}
</body>
</html>

django_garden/garden/templates/pages/home.html
{% extends 'base.html' %}


{% block content %}
    <div class="jumbotron">
        <h1 class="display-3">Hola mundo!</h1>
        <p class="lead">Este es un jardín inteligente creado por un nerd con mucho tiempo libre.</p>
        <hr class="my-4">
        <p class="lead">
            Aquí va una explicación la cual no he hecho jeje
        </p>
        <a href="{% url 'sensors:all_sensors' %}" class="btn btn-lg btn-danger"><i class="fa fa-rocket"></i> Ver la información de los sensores</a>
    </div>
{% endblock content %}

django_garden/garden/templates/sensors/all_sensors.html
{% extends "base.html" %}

{% block content %}
<div class="row mt-5">
    <div class="col-md-4">
        <div class="card text-white mb-3 bg-danger" style="max-width: 20rem;">
            <div class="card-header">LM35</div>
            <div class="card-body">
                <h4 class="card-title"><i class="fa fa-thermometer-empty"></i> Temperatura del suelo</h4>
                <p class="card-text">La temperatura cerca de las plantas</p>
                {% if lm_temp %}
                    <div class="alert alert-primary">
                        <h3 class="alert-heading">{{lm_temp}}° C</h3>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card text-white mb-3 bg-primary" style="max-width: 20rem;">
            <div class="card-header">DHT11</div>
            <div class="card-body">
                <h4 class="card-title"><i class="fa fa-tint"></i> Humedad del ambiente</h4>
                <p class="card-text">El porcentaje de humedad del ambiente</p>
                {% if dh_humidity %}
                    <div class="alert alert-info">
                        <h3 class="alert-heading">{{dh_humidity}}%</h3>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card text-white mb-3 bg-primary" style="max-width: 20rem;">
            <div class="card-header">DHT11</div>
            <div class="card-body">
                <h4 class="card-title"><i class="fa fa-tint"></i> Temperatura del ambiente</h4>
                <p class="card-text">La temperatura ambiente del jardín</p>
                {% if dh_temp %}
                    <div class="alert alert-danger">
                        <h3 class="alert-heading">{{dh_temp}}° C</h3>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card text-white mb-3 bg-warning" style="max-width: 20rem;">
            <div class="card-header">Soil Moisture Sensor</div>
            <div class="card-body">
                <h4 class="card-title"><i class="fa fa-tint"></i> Humedad</h4>
                <p class="card-text">El nivel de humedad del suelo</p>
                <div class="alert alert-info">
                    <h3 class="alert-heading">Aún no lo calibro jeje</h3>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

django_garden/garden/templates/sensors/data.html
{% extends "base.html" %} 

{% block content %}
<div class="row mt-5">
    {% for temperature in temperature_list %}
        
    {% endfor %}
</div>
{% endblock %}